#!/bin/bash

# Using 3/4 GB for shared memory
SHARED_MAX=$((768 * 1024 * 1024))
SHARED_ALL=$((768 * 1024 * 1024 / 4096))

# Cloud 9 container does not allow access to sysctl.conf
# and limits are already high
# echo "Setting shmmax to $SHARED_MAX"
# echo "Setting shmall to $SHARED_ALL"
# echo "kernel.shmmax = $SHARED_MAX" >> /etc/sysctl.conf
# echo "kernel.shmall = $SHARED_ALL" >> /etc/sysctl.conf
# sysctl -p

# Update apt-get and install basic tools
sudo apt-get update -qq
sudo apt-get install -y xauth git curl

# Run the GAMESS installation script
chmod u+x install-gamess.sh
./install-gamess.sh $(pwd)/gamess-built.tar.gz
